name: Lint and Commit Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Commitlint
      uses: wagoid/commitlint-github-action@v4

    - name: Lint with eslint
      run: npm run lint
